services:
  # A Docker web service
  - type: web
    name: webdis
    env: docker
    repo: https://github.com/depezo/aki/server.git
    plan: free
    branch: main
    envVars:
      - key: PORT
        value: 3000
